### PR TITLE
[WIP] remove unnecessary pkgs in Dockerfile

### LINKED ISSUE #40: Dockerfile shouldn't include requirement of SQLFlow
`gohive` is a standalone repo. Its Dockerfile shouldn't include the requirement of SQLFlow.

https://github.com/sql-machine-learning/gohive/blob/724039315edec1f08aa2480176e450931161f7b8/docker/Dockerfile#L167-L174

If SQLFlow want to reuse this Dockerfile, please build from `FROM sqlflow/gohive:dev`.

### PR DESCRIPTION
**Pull request by weiguoz**
fix #40

### CODE REVIEW

**Comment by typhoonzero** [comment]
We should update sqlflow to not use this image directly first before removing these deps: https://github.com/sql-machine-learning/sqlflow/blob/develop/.travis.yml#L33

**Comment by tonyyang-svail** [comment]
https://github.com/sql-machine-learning/gohive/blob/724039315edec1f08aa2480176e450931161f7b8/docker/Dockerfile#L146

Should also be reverted.

Note: if you wanna undo a commit message (https://github.com/sql-machine-learning/gohive/commit/724039315edec1f08aa2480176e450931161f7b8 ) by appending a new commit with the resulting inverse content, try `git revert`. [ref](https://www.atlassian.com/git/tutorials/undoing-changes/git-revert)

**Review by typhoonzero — CHANGES_REQUESTED** [review]
Discussed with @weiguoz I'll try to put hive server container at background in CI, so that we can remove deps here.

**Comment by tonyyang-svail** [comment]
Duplicated with https://github.com/sql-machine-learning/gohive/pull/42. Since this PR is titled with WIP, I choose to close this one.

**Pull request closed without merging**
