### PR TITLE
Go imports

### PR DESCRIPTION
**Pull request by wangkuiyi**
As a followup of the [vanity Go import path work](https://github.com/sql-machine-learning/sqlflow/issues/260), we need to either remove our `vendor` directory, wait for https://github.com/bramp/goredirects/pull/6 to merge, or do many error-prone manual work to setup `sqlflow.org`.   Considering that we have only a certain version of Thrift in our `vendor` directory, which is a dependent of HIveServer2 and doesn't seem to be changed frequently, if not ever, I think it is alright just get that certain version of Thrift out of the `vendor` directory and move it to `/git.apache.org/thrift.git`.

Accordingly, I changed Go import paths:

1. `github.com/sql-machine-learning/gohive` => `sqlflow.org/gohive`
1. `github.com/sql-machine-learning/gohive/vendor/git.apache.org` => `sqlflow.org/gohive/git.apache.org`.

I also updated `/dockerfile/README.md`, which describes how to build and run GoHive in a Docker container, into `docker/README.md`.  I changed the directory name because there are more than a Dockerfile in that directory, but all should be copied into the Docker image.

I added `/README.md`, which has a link to `docker/README.md` for developers.

### CODE REVIEW

**Review by tonyyang-svail — CHANGES_REQUESTED** [review]
Should we use `sqlflow.org` or `sqlflow.dev`?

The https://github.com/sql-machine-learning/sqlflow/issues/260#issuecomment-481946261 was suggesting `sqlflwo.dev`.

**Comment by wangkuiyi** [comment]
@tonyyang-svail let us just do sqlflow.org. No need to require contributors to remember two domain names. https://github.com/sql-machine-learning/sqlflow/issues/260#issuecomment-482359790

**Comment by tonyyang-svail** [comment]
> I also updated /dockerfile/README.md, which describes how to build and run GoHive in a Docker container, into docker/README.md. I changed the directory name because there are more than a Dockerfile in that directory, but all should be copied into the Docker image.

I agree with the rename. Could you file these changes in a separate PR?

> I added /README.md, which has a link to docker/README.md for developers.

Thanks for adding the README. Could you file these changes in a separate PR?

**Comment by wangkuiyi** [comment]
My changes to all these README.md are mostly due to the renaming. It doesn't make sense to separate them into different PRs.

**Comment by tonyyang-svail** [comment]
~~My local `go get` failed as~~
```
$ go get sqlflow.org/gohive
package sqlflow.org/gohive: unrecognized import path "sqlflow.org/gohive" (https fetch: Get https://sqlflow.org/gohive?go-get=1: EOF)
```
My local `go get` failed as
```
$ go get sqlflow.org/gohive
# sqlflow.org/gohive
src/sqlflow.org/gohive/driver.go:33:51: cannot use protocol (type *"sqlflow.org/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TBinaryProtocolFactory) as type "github.com/sql-machine-learning/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TProtocolFactory in argument to tcliservice.NewTCLIServiceClientFactory:
	*"sqlflow.org/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TBinaryProtocolFactory does not implement "github.com/sql-machine-learning/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TProtocolFactory (wrong type for GetProtocol method)
		have GetProtocol("sqlflow.org/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TTransport) "sqlflow.org/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TProtocol
		want GetProtocol("github.com/sql-machine-learning/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TTransport) "github.com/sql-machine-learning/gohive/vendor/git.apache.org/thrift.git/lib/go/thrift".TProtocol
```
However, I believe this issue can be solved after this PR is merged.

**Review by yuyicg — APPROVED** [review]

**Review by tonyyang-svail — APPROVED** [review]

**Pull request merged**
